package com.latlon.test.models;
// Generated Oct 11, 2018 6:31:29 PM by Hibernate Tools 5.3.6.Final

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer id;
	private String name;
	private String country;
	private Integer phNo;

	public Person() {
	}

	public Person(String name) {
		this.name = name;
	}

	public Person(String name, String country, Integer phNo) {
		this.name = name;
		this.country = country;
		this.phNo = phNo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Integer getPhNo() {
		return this.phNo;
	}

	public void setPhNo(Integer phNo) {
		this.phNo = phNo;
	}

}
