package com.latlon.test.models;
// Generated Oct 12, 2018 2:10:24 PM by Hibernate Tools 5.3.6.Final

import java.math.BigDecimal;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer slno;
	private Integer pid;
	private String address;
	private String street;
	private String city;
	private String state;
	private String country;
	private BigDecimal latitude;
	private BigDecimal longitude;

	public Address() {
	}

	public Address(Integer pid, String address, String street, String city, String state, String country,
			BigDecimal latitude, BigDecimal longitude) {
		this.pid = pid;
		this.address = address;
		this.street = street;
		this.city = city;
		this.state = state;
		this.country = country;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Integer getSlno() {
		return this.slno;
	}

	public void setSlno(Integer slno) {
		this.slno = slno;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

}
